# Generated by Django 4.1.4 on 2023-01-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firtname', models.CharField(max_length=500)),
                ('lastname', models.CharField(max_length=500)),
                ('age', models.IntegerField()),
                ('Homeland', models.CharField(max_length=500)),
            ],
        ),
    ]
